name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-nd-github-actions-app-${{ github.run_id }}-${{ github.run_attempt }}
      - image:arm-3.0
      - instance-size:small
    steps:
      - run: echo "Hello World!"
