name: Hello World
on: [push]
jobs:
  Run-Terraform-I-Different-Account:
    runs-on:
      - codebuild-github_project-${{ github.run_id }}-${{ github.run_attempt }}
      - image:arm-3.0
      - instance-size:small
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          role-to-assume: arn:aws:iam::874500785305:role/codebuild-service-role
          role-session-name: AssumeRoleSession
          aws-region: us-east-1
      - run: | 
        aws sts get-caller-identity
        terraform -chdir=./terraform init --backend-config=config/dev.config
