name: On Merge
on: 
  push:
    branches:
      - 'main'
jobs:
  On_Merge:
    uses: srhoton/srhoton-nd-github-actions-templates/.github/workflows/on_merge.yml@repo_branch
    with: 
      repository: ${{ github.event.repository.name }}
