name: On Push
on: 
  merge:
    branches:
      - 'main'
jobs:
  On_Push:
    uses: srhoton/srhoton-nd-github-actions-templates/.github/workflows/on_merge.yml@templates_setup
    with:
      environment: ${{ github.head_ref || github.ref_name }}
