name: On Tag
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  On_Tag:
    uses: srhoton/srhoton-nd-github-actions-templates/.github/workflows/on_tag.yml@main
    with:
      repository: ${{ github.event.repository.name }}
